language: node_js
node_js:
  - 12
deploy:
  provider: firebase
env:
  global:
    secure: KpIXOfx0nCHLH2GyQ9V9nL30hvMnD3bqCLxAIqtA8S0nXwLvbB+vrWwTdKI6W/sxn86xeo5Y0FXqcXNaqweRpiJa3r5YKL8yXCQAYktXSPl9DmFTae2dZWHfO4HMYrRM0mFTbK1I4+dD2t4dCpL8QcSPf56dY0tCVX/usSAoBpaPUAioDsTcvm7w8UkOo2VVFkZajcqkejRIbqfsL4fT40A2YeQjfax3Q3BgUu5/ShjnhfaRC1Te2MVt3Bq49/GTJZWppVrmkCctsXmVuNiV8bvqGsGWRyRLVADf51UdSSuc343SY8y2CHElryUtU/FztN7IB5PVPGUItZ57k8KYAA+lfk8OQM3UuOxfaXrdUwF7bRonteYaymom7BDr5Cunicn4W85fjPo/nDXkrtTfzIm3OasZtukInPLqlPbR4pPtxPadiqgi4izzP6VUbKJtftHW8DzZwB/HIE7RH93bEGFQiwmfO9m/XGzY1HK2RymNlAqkm9aXAOGpgmoI3pisFrPe2wiSFatC82G5/vEWmFwuh7YrNWdJwNSZmEbENfVxnop99mAzB87d9600afyOsG4ZZcsV/UmXGGJSyK7bmT26Vz/BUevNzfm4qooEcNelear0GTYClIAh3FiM8FruIdGWIPd19AhBAXSNLGh2i4O+jAs901ZXOWsouX5L0bI=
